name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging Ivista
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # Your server's SSH password

          script: |
            cd /home/react-staging/ivistaz
            echo ${{ secrets.PASSWORD }} | sudo -S git config --global --add safe.directory /home/react-staging/ivistaz
            echo ${{ secrets.PASSWORD }} | sudo -S git pull origin main
            echo ${{ secrets.PASSWORD }} | sudo -S npm install
            echo ${{ secrets.PASSWORD }} | sudo -S npm run build
